### ISSUE TITLE
Check for VK_AMD_device_coherent_memory support at the runtime

### ISSUE THREAD

**Issue by werman** [googlestadia/gfr#5]
There is an `EnforceCoherentMemory` variable which controls whether to enforce this extension, however it would be better to check if extension is supported at the run time.

I found this tool to be useful while debugging hangs on Turnip driver (open-source Vulkan driver for Adreno) and we don't support `VK_AMD_device_coherent_memory`.

**Comment by aellem** [comment]
It makes sense to do this check, it's just cleaner.

I assume that Turnip supported the buffer marker extension then?

**Comment by werman** [comment]
> I assume that Turnip supported the buffer marker extension then?

It's not yet merged but yes (https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/13553).
